services:
    omnipay:
        class: Xola\OmnipayBundle\Service\Omnipay
        arguments:
            - '@service_container'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: omnipay }
