parameters:
    omnipay.service.class: Xola\OmnipayBundle\Service\Omnipay

services:
    Xola\OmnipayBundle\Service\Omnipay:
        arguments:
            - "@service_container"
            - "@logger"
        tags:
            - { name: monolog.logger, channel: omnipay }

    omnipay:
        alias: Xola\OmnipayBundle\Service\Omnipay
        public: true
