language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2

env:
  - SYMFONY_VERSION="4.4"
  - SYMFONY_VERSION="5.4"
  - SYMFONY_VERSION="6.0"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install -n --prefer-source

script: phpunit --coverage-text --configuration phpunit.xml.dist
